# Generated by Django 4.1.13 on 2026-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemdulich',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
