# Generated by Django 4.1.13 on 2026-01-28 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_diemdulich_hinh_anh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhgia',
            options={'ordering': ['-ngay_danh_gia']},
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='diem_du_lich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='app.diemdulich'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='ngay_danh_gia',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='so_sao',
            field=models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')]),
        ),
        migrations.AlterUniqueTogether(
            name='danhgia',
            unique_together={('nguoi_dung', 'diem_du_lich')},
        ),
    ]
